<?php

return [
    ['Sunshine Apartments', 'Pampanga', 'Angeles City', 'Sto. Domingo', '123 Rizal Street', 'A well-maintained apartment complex near SM Clark with 24/7 security and CCTV surveillance.'],
    ['Greenview Residences', 'Pampanga', 'Mabalacat City', 'Dolores', '456 Mabiga Road', 'Affordable residential units in a quiet neighborhood perfect for young professionals and families.'],
    ['Clark Heights', 'Pampanga', 'Angeles City', 'Malabanias', '789 Fields Avenue', 'Modern living spaces near Clark Freeport Zone with easy access to commercial areas.'],
    ['Villa San Fernando', 'Pampanga', 'City of San Fernando', 'Sindalan', '12 MacArthur Highway', 'Comfortable units in the heart of San Fernando city with nearby schools and markets.'],
    ['Pampanga Garden Suites', 'Pampanga', 'City of San Fernando', 'Telabastagan', '34 San Agustin Street', 'Garden-themed residential complex with landscaped areas and covered parking.'],
    ['Metro Angeles Flats', 'Pampanga', 'Angeles City', 'Pulungbulu', '56 Friendship Avenue', 'Convenient urban living near transportation hubs and commercial centers.'],
    ['Sunset View Residences', 'Pampanga', 'Angeles City', 'Sapang Bato', '78 Sapang Bato Road', 'Peaceful residential community with beautiful sunset views and cool breeze.'],
    ['Clark Business Suites', 'Pampanga', 'Angeles City', 'Balibago', '90 Santos Street', 'Perfect for business travelers and professionals working in the Clark area.'],
    ['Pampanga Homes', 'Pampanga', 'City of San Fernando', 'Del Pilar', '11 Del Pilar Street', 'Family-friendly residential complex with playground and community area.'],
    ['Angeles Garden Villas', 'Pampanga', 'Angeles City', 'Lourdes Sur', '22 Garden Road', 'Premium garden villas with spacious units and well-maintained surroundings.'],
    ['SM Clark Residences', 'Pampanga', 'Angeles City', 'Ninoy Aquino', '33 Aquino Street', 'Walking distance to SM Clark and other major commercial establishments.'],
    ['Mabalacat Suites', 'Pampanga', 'Mabalacat City', 'Poblacion', '44 Poblacion Road', 'Centrally located suites in Mabalacat with easy access to NLEX and main roads.'],
    ['Pampanga Heritage Homes', 'Pampanga', 'City of San Fernando', 'San Nicolas', '55 Heritage Avenue', 'Heritage-inspired residential complex with modern amenities and facilities.'],
    ['Clark Investors Hub', 'Pampanga', 'Angeles City', 'Margot', '66 Clark Avenue', 'Investor-grade units with high rental yield potential near Clark economic zone.'],
    ['Holy Family Residences', 'Pampanga', 'Angeles City', 'Holy Family', '77 Holy Family Road', 'Peaceful and secure residential complex near Holy Family Parish Church.'],
    ['Nepo Quad Apartments', 'Pampanga', 'Angeles City', 'Pulung Maragul', '88 Nepo Road', 'Modern apartments near Nepo Mall and Robinsons Starmills Pampanga.'],
    ['Diamond Residences', 'Pampanga', 'Angeles City', 'Cutcut', '99 Diamond Street', 'Premium residential units with diamond-class amenities and 24/7 security.'],
    ['Friendship Village', 'Pampanga', 'Angeles City', 'Friendship', '100 Friendship Road', 'Well-established residential community with complete utilities and facilities.'],
    ['Pampanga Central Flats', 'Pampanga', 'City of San Fernando', 'San Jose', '111 Central Avenue', 'Centrally located flats with easy access to government offices and commercial areas.'],
    ['Angeles Heights', 'Pampanga', 'Angeles City', 'Anunas', '122 Heights Drive', 'Elevated residential complex with panoramic views and cool mountain breeze.'],
    ['Starmills Residences', 'Pampanga', 'City of San Fernando', 'San Isidro', '133 Starmills Road', 'Modern living near Robinsons Starmills and other major shopping centers.'],
    ['Clark Green City Homes', 'Pampanga', 'Angeles City', 'Capaya', '144 Green City Drive', 'Eco-friendly residential complex with green spaces and sustainable facilities.'],
    ['Apalit River View', 'Pampanga', 'Apalit', 'San Vicente', '155 Riverside Road', 'Scenic river view units perfect for nature lovers and peaceful living.'],
    ['Guagua Modern Flats', 'Pampanga', 'Guagua', 'Poblacion', '166 Guagua Road', 'Modern residential flats in the historic town of Guagua with complete amenities.'],
    ['Bacolor Heritage Suites', 'Pampanga', 'Bacolor', 'San Pablo', '177 Heritage Road', 'Heritage-inspired suites in the historic town of Bacolor, Pampanga.'],
    ['Floridablanca Garden Homes', 'Pampanga', 'Floridablanca', 'Poblacion', '188 Garden Drive', 'Garden homes in the peaceful town of Floridablanca with fresh air and nature.'],
    ['Porac Mountain View', 'Pampanga', 'Porac', 'Poblacion', '199 Mountain Road', 'Mountain view residential units in Porac with cool climate and fresh environment.'],
    ['Lubao Riverside Homes', 'Pampanga', 'Lubao', 'San Antonio', '200 Riverside Drive', 'Riverside residential homes in Lubao with scenic views and peaceful ambiance.'],
    ['Sasmuan Coastal Living', 'Pampanga', 'Sasmuan', 'Malusac', '211 Coastal Road', 'Unique coastal living experience near Sasmuan Coastal Wetlands.'],
    ['Mexico Town Residences', 'Pampanga', 'Mexico', 'Poblacion', '222 Town Road', 'Affordable residential units in the progressive town of Mexico, Pampanga.'],
    ['Magalang Hillside Homes', 'Pampanga', 'Magalang', 'Camias', '233 Hillside Drive', 'Hillside homes in Magalang with cool climate and scenic mountain views.'],
    ['Candaba Wetlands Villas', 'Pampanga', 'Candaba', 'Poblacion', '244 Wetlands Road', 'Unique villas near Candaba Wetlands, perfect for nature enthusiasts.'],
    ['Sta. Ana Modern Suites', 'Pampanga', 'Santa Ana', 'Poblacion', '255 Modern Street', 'Modern suites in the quiet town of Sta. Ana with complete basic amenities.'],
    ['Masantol Waterfront Homes', 'Pampanga', 'Masantol', 'Sagrada Familia', '266 Waterfront Road', 'Waterfront residential homes in Masantol with beautiful river views.'],
    ['Macabebe Riverside Flats', 'Pampanga', 'Macabebe', 'Poblacion', '277 Riverside Street', 'Affordable riverside flats in Macabebe with easy access to main roads.'],
    ['Minalin Peaceful Homes', 'Pampanga', 'Minalin', 'Poblacion', '288 Peaceful Drive', 'Peaceful residential homes in the quiet town of Minalin, Pampanga.'],
    ['Sto. Tomas Garden Units', 'Pampanga', 'Santo Tomas', 'Poblacion', '299 Garden Street', 'Garden units in the progressive municipality of Sto. Tomas, Pampanga.'],
    ['San Luis Valley Homes', 'Pampanga', 'San Luis', 'Poblacion', '300 Valley Road', 'Valley view homes in San Luis with fresh air and peaceful environment.'],
    ['San Simon Riverside', 'Pampanga', 'San Simon', 'Poblacion', '311 Riverside Avenue', 'Riverside residential units in San Simon with scenic views and cool breeze.'],
    ['Sta. Rita Modern Flats', 'Pampanga', 'Santa Rita', 'Poblacion', '322 Modern Road', 'Modern residential flats in Sta. Rita with complete utilities and amenities.'],
    ['Betis Heritage Homes', 'Pampanga', 'Guagua', 'Betis', '333 Heritage Street', 'Heritage-inspired homes in the historic barangay of Betis, Guagua.'],
    ['Del Carmen Suites', 'Pampanga', 'City of San Fernando', 'Del Carmen', '344 Del Carmen Road', 'Modern suites in Del Carmen with easy access to SM Pampanga and NLEX.'],
    ['Dolores Residential Park', 'Pampanga', 'City of San Fernando', 'Dolores', '355 Park Avenue', 'Residential park with green spaces and family-friendly environment.'],
    ['San Agustin Modern Homes', 'Pampanga', 'City of San Fernando', 'San Agustin', '366 San Agustin Road', 'Modern homes in San Agustin with complete amenities and 24/7 security.'],
    ['San Felipe Garden Villas', 'Pampanga', 'City of San Fernando', 'San Felipe', '377 Garden Villa Road', 'Garden villas in San Felipe with landscaped surroundings and parking.'],
    ['San Juan Residential Hub', 'Pampanga', 'City of San Fernando', 'San Juan', '388 Hub Street', 'Residential hub in San Juan strategically located near commercial areas.'],
    ['San Pedro Valley Homes', 'Pampanga', 'City of San Fernando', 'San Pedro', '399 Valley Drive', 'Valley homes in San Pedro with mountain views and cool climate.'],
    ['Santiago Premium Suites', 'Pampanga', 'City of San Fernando', 'Santiago', '400 Premium Road', 'Premium suites in Santiago with high-end finishes and modern amenities.'],
    ['Quebiawan Modern Flats', 'Pampanga', 'City of San Fernando', 'Quebiawan', '411 Modern Flat Road', 'Modern flats in Quebiawan near Robinsons Starmills and main commercial areas.'],
    ['Sindalan Garden Residences', 'Pampanga', 'City of San Fernando', 'Sindalan', '422 Garden Residence Road', 'Garden residences in Sindalan with lush greenery and peaceful environment.'],
    ['Lourdes Sur East Homes', 'Pampanga', 'Angeles City', 'Lourdes Sur East', '433 East Road', 'Modern homes in Lourdes Sur East with easy access to Clark and commercial areas.'],
];
